name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # At 12:00 AM, only on Monday (https://crontab.cronhub.io/)
    - cron: "0 0 * * 1"
jobs:
  waka-readme-stats-update:
    name: Update Readme with waka-readme-stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka-readme-stats-total
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: True
          
          SHOW_PROJECTS: True


  waka-readme-update:
    name: Update Readme with waka-readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: waka-readme-total
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          TIME_RANGE: all_time
          BLOCKS: ░▓
